back/flopedt-django/api/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework import routers

import api.base.views as views_base
import api.fetch.views as views_fetch
from api import views
from api.base.courses.urls import routerCourses
from api.base.groups.urls import routerGroups
from api.base.rooms.urls import routerRooms
from api.base.urls import url_base_patterns
from api.fetch.urls import routerFetch
from api.people.urls import url_user_patterns
from api.TTapp.urls import routerTTapp
from api.celcat.urls import routerCelcat

# V1...
from api.v1.urls import url_V1_patterns

#####################################
# URLS based on django applications #
#####################################

app_name = "api"

routerDisplayweb = routers.SimpleRouter()

routerDisplayweb.register(r"breakingnews", views.BreakingNewsViewSet)
routerDisplayweb.register(r"moduledisplays", views.ModuleDisplaysViewSet)
routerDisplayweb.register(
    r"trainingprogrammedisplays", views.TrainingProgrammeDisplaysViewSet
)
routerDisplayweb.register(r"groupdisplays", views.GroupDisplaysViewSet)

######################
# User friendly URLS #
######################

routerExtra = routers.SimpleRouter()

routerExtra.register("bknews", views_fetch.BKNewsViewSet, basename="bknews")
routerExtra.register("quote/random", views.RandomQuoteViewSet, basename="random-quote")
routerExtra.register("quote", views.QuoteViewSet)
routerExtra.register("week-infos", views.WeekInfoViewSet, basename="week-infos")

################
# SWAGGER VIEW #
################


urlpatterns = [
    path("", views_base.LoginView.as_view(), name="api_root"),
    path("logout/", views_base.LogoutView.as_view()),
    path(
        "backoffice/", login_required(TemplateView.as_view(template_name="logout.html"))
    ),
    path("base/", include((url_base_patterns, "api"), namespace="base")),
    path("user/", include((url_user_patterns, "api"), namespace="people")),
    # path("display/", include(routerDisplayweb.urls)),
    path("ttapp/", include((routerTTapp.urls, "api"), namespace="ttapp")),
    path("fetch/", include((routerFetch.urls, "api"), namespace="fetch")),
    # path("rest-auth/", include("dj_rest_auth.urls")),
    # path("api-token-auth/", obtain_auth_token, name="api_token_auth"),
    path("rooms/", include((routerRooms.urls, "api"), namespace="rooms")),
    path("courses/", include((routerCourses.urls, "api"), namespace="course")),
    path("groups/", include((routerGroups.urls, "api"), namespace="groups")),
    # path("extra/", include((routerExtra.urls, "api"), namespace="extra")),
    # path(
    #     "roomreservations/",
    #     include((routerRoomReservation.urls, "api"), namespace="roomreservations"),
    # ),
    path("v1/", include((url_V1_patterns, "api"), namespace="V1")),
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "doc/",
        SpectacularSwaggerView.as_view(url_name="api:schema"),
        name="swagger-ui",
    ),
    path("celcat/", include((routerCelcat.urls, "api"), namespace="celcat")),
]

back/flopedt-django/flop_ics/urls.py
from django.urls import path

from flop_ics import views
from flop_ics.feeds import (
    RegenFeed,
    RoomEventFeed,
    StructuralGroupEventFeed,
    TransversalGroupEventFeed,
    TutorEventFeed,
)

app_name = "flop_ics"

urlpatterns = [
    path(r"", views.index, name="index"),
    path(r"tutor/<int:tutor_id>.ics", TutorEventFeed(), name="tutor"),
    path(r"room/<int:room_id>.ics", RoomEventFeed(), name="room"),
    path(
        r"structural_group/<int:group_id>.ics",
        StructuralGroupEventFeed(),
        name="structural_group",
    ),
    path(
        r"transversal_group/<int:group_id>.ics",
        TransversalGroupEventFeed(),
        name="transversal_group",
    ),
    path(r"regen/<int:dep_id>.ics", RegenFeed(), name="regen"),
]

back/flopedt-django/flop_ics/models.py
# from django.db import models

# Create your models here.

back/flopedt-django/flop_ics/views.py
from django.shortcuts import render

from base import queries
from base.models import Department, StructuralGroup, TransversalGroup
from people.models import Tutor


def index(request, **kwargs):
    tutor_list = (
        Tutor.objects.filter(
            is_active=True, is_tutor=True, departments=request.department
        )
        .prefetch_related("departments")
        .order_by("username")
    )
    structural_group_list = (
        StructuralGroup.objects.filter(
            basic=True, train_prog__department=request.department
        )
        .select_related("train_prog__department")
        .order_by("train_prog__abbrev", "name")
    )
    transversal_group_list = (
        TransversalGroup.objects.filter(train_prog__department=request.department)
        .select_related("train_prog__department")
        .order_by("train_prog__abbrev", "name")
    )
    room_list = [
        {"name": n.name, "id": n.id}
        for n in queries.get_rooms(request.department.abbrev, basic=True).order_by(
            "name"
        )
    ]
    deps = Department.objects.all()
    # We consider suffix length to avoid ics link representation
    # suffix_length = len(request.department.abbrev) + 9
    context = {
        "tutors": tutor_list,
        "structural_groups": structural_group_list,
        "transversal_groups": transversal_group_list,
        "rooms": room_list,
        "deps": deps,
        # 'requi': request.build_absolute_uri()[:-suffix_length]
    }
    return render(request, "flop_ics/index.html", context=context)

back/flopedt-django/flop_ics/templates/flop_ics/index.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}
{% load i18n %}

{% block title %} EDT {% endblock %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static "base/better.css" %}"/>

<div id="tools-main" style="padding:10px;">

    <h2>{% trans "iCal Subscription" %}</h2>
    <p>{% trans "Copy the corresponding link of the calendar you would like to add to your calendar manager." %}</p>
    
    <h2>{% trans "Groups" %}</h2>
        <ul>
            <h3>{% trans "Structural" %}</h3>
            <table>
              <th>{% trans "Training program" %}</th><th>{% trans "Group name" %}</th>
              {% for g in structural_groups %}
                  <tr>
                     <td>{{ g.train_prog.abbrev }}</td>
                     <td>{{ g.name }}</td>
                     <td><a href="{% url "flop_ics:structural_group" department g.id %}">{% trans "Copy this link" %} - {{ g.name }}</a></td>
                  </tr>
              {% endfor %}
            </table>
            {% if transversal_groups %}
                <h3>{% trans "Transversal" %}</h3>
                <table>
                    <th>{% trans "Training program" %}</th><th>{% trans "Group name" %}</th>
                    {% for g in transversal_groups %}
                        <tr>
                        <td>{{ g.train_prog.abbrev }}</td>
                        <td>{{ g.name }}</td>
                        <td><a href="{% url "flop_ics:transversal_group" department g.id %}">{% trans "Copy this link" %} - {{ g.name }}</a></td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}
        </ul>

    <h2>{% trans "Tutors" %}</h2>
    <ul>
      <table>
        <tr><th>{% trans "Pseudo" %}</th><th>{% trans "First name" %}</th><th>{%  trans "Last lame" %}</th><th>{% trans "Department(s)" %}</th><th>{% trans "Address" %}</th></tr>
	{% for e in tutors %}
	<tr>
          <td>{{ e.username }}</td>
          <td>{{ e.first_name }}</td>
          <td>{{ e.last_name }}</td>
          <td>{{ e.departments.all | join:", " }}</td>
          <td><a href="{% url "flop_ics:tutor" department e.id %}">{% trans "Copy this link" %} - {{ e.username }}</a></td>
        </tr>
	{% endfor %}
      </table>
    </ul>
	
    <h2>{% trans "Rooms" %}</h2>
    <ul>
      <table>
        <tr><th>{% trans "Name" %}</th><th>{% trans "Address" %}</th></tr>
        {% for s in rooms %}
        <tr>
          <td>{{ s.name }}</td>
          <td><a href="{% url "flop_ics:room" department s.id %}">{% trans "Copy this link" %} - {{ s.name }}</a></td>
        </tr>
        {% endfor %}
      </table>
    </ul>

    <h2>{% trans "Planned generations" %}</h2>
    <ul>
      <table>
        <tr><th>{% trans "Department" %}</th><th>{% trans "Address" %}</th></tr>
        {% for d in deps %}
        <tr>
          <td>{{ d.abbrev }}</td>
          <td><a href="{% url "flop_ics:regen" department d.id%}">{% trans "Copy this link" %} - {{ d.abbrev }}</a></td>
        </tr>
        {% endfor %}
      </table>
    </ul>

</div>
{% endblock %}