back/flopedt-django/api/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.
from django.urls import path
from rest_framework import routers

from api.base import views

routerBase = routers.SimpleRouter()

# routerBase.register(r'studentspreferences', views.StudentPreferencesViewSet, basename="students")
# routerBase.register(r'groupspreferences', views.GroupPreferencesViewSet)

# routerBase.register(r'departments', views.DepartmentViewSet)
routerBase.register(
    r"trainingprogram/name",
    views.TrainingProgrammeNameViewSet,
    basename="trainingprogramme-name",
)
# routerBase.register(r'trainingprogram', views.TrainingProgrammeViewSet)
# routerBase.register(r'holidays', views.HolidaysViewSet)
# routerBase.register(r'traininghalfdays', views.TrainingHalfDaysViewSet)
routerBase.register(r"trainingperiods", views.TrainingPeriodsViewSet, basename="trainingperiods")
routerBase.register(r"timesettings", views.TimeGeneralSettingsViewSet, basename="timesettings")
routerBase.register(r"weeks", views.SchedulingPeriodsViewSet, basename="weeks")
routerBase.register(r"periods", views.SchedulingPeriodsViewSet, basename="periods")
# routerBase.register(r'timetableversions', views.TimetableVersionsViewSet)
# routerBase.register(r'coursemodifications', views.CourseModificationsViewSet)
# routerBase.register(r'tutorcosts', views.TutorCostsViewSet)
# routerBase.register(r'groupcosts', views.GroupCostsViewSet)
# routerBase.register(r'CourseStartTimeFilter', views.GroupFreeHalfDaysViewSet)
# routerBase.register(r'dependencies', views.DependenciesViewSet)
# routerBase.register(r'regens', views.RegensViewSet)
# routerBase.register(r'login', views.LoginView, basename="login")
# routerBase.register(r'logout', views.LogoutView, basename="logout")
url_base_patterns = [
    path(r"contact", views.ContactView.as_view(), name="contactMail"),
]

url_base_patterns += routerBase.urls

back/flopedt-django/api/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework import routers

import api.base.views as views_base
import api.fetch.views as views_fetch
from api import views
from api.base.courses.urls import routerCourses
from api.base.groups.urls import routerGroups
from api.base.rooms.urls import routerRooms
from api.base.urls import url_base_patterns
from api.fetch.urls import routerFetch
from api.people.urls import url_user_patterns
from api.TTapp.urls import routerTTapp
from api.celcat.urls import routerCelcat

# V1...
from api.v1.urls import url_V1_patterns

#####################################
# URLS based on django applications #
#####################################

app_name = "api"

routerDisplayweb = routers.SimpleRouter()

routerDisplayweb.register(r"breakingnews", views.BreakingNewsViewSet)
routerDisplayweb.register(r"moduledisplays", views.ModuleDisplaysViewSet)
routerDisplayweb.register(
    r"trainingprogrammedisplays", views.TrainingProgrammeDisplaysViewSet
)
routerDisplayweb.register(r"groupdisplays", views.GroupDisplaysViewSet)

######################
# User friendly URLS #
######################

routerExtra = routers.SimpleRouter()

routerExtra.register("bknews", views_fetch.BKNewsViewSet, basename="bknews")
routerExtra.register("quote/random", views.RandomQuoteViewSet, basename="random-quote")
routerExtra.register("quote", views.QuoteViewSet)
routerExtra.register("week-infos", views.WeekInfoViewSet, basename="week-infos")

################
# SWAGGER VIEW #
################


urlpatterns = [
    path("", views_base.LoginView.as_view(), name="api_root"),
    path("logout/", views_base.LogoutView.as_view()),
    path(
        "backoffice/", login_required(TemplateView.as_view(template_name="logout.html"))
    ),
    path("base/", include((url_base_patterns, "api"), namespace="base")),
    path("user/", include((url_user_patterns, "api"), namespace="people")),
    # path("display/", include(routerDisplayweb.urls)),
    path("ttapp/", include((routerTTapp.urls, "api"), namespace="ttapp")),
    path("fetch/", include((routerFetch.urls, "api"), namespace="fetch")),
    # path("rest-auth/", include("dj_rest_auth.urls")),
    # path("api-token-auth/", obtain_auth_token, name="api_token_auth"),
    path("rooms/", include((routerRooms.urls, "api"), namespace="rooms")),
    path("courses/", include((routerCourses.urls, "api"), namespace="course")),
    path("groups/", include((routerGroups.urls, "api"), namespace="groups")),
    # path("extra/", include((routerExtra.urls, "api"), namespace="extra")),
    # path(
    #     "roomreservations/",
    #     include((routerRoomReservation.urls, "api"), namespace="roomreservations"),
    # ),
    path("v1/", include((url_V1_patterns, "api"), namespace="V1")),
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "doc/",
        SpectacularSwaggerView.as_view(url_name="api:schema"),
        name="swagger-ui",
    ),
    path("celcat/", include((routerCelcat.urls, "api"), namespace="celcat")),
]

back/flopedt-django/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.urls import path, re_path

from . import views

app_name = "base"

urlpatterns = [
    # favicon
    # ----------------------------
    re_path(views.FAV_REGEXP, views.favicon, name="favicon"),
    # directly reachable by users
    # ----------------------------
    re_path(
        r"room-preference/(?P<tutor>\w{2,8})?/", views.room_preference, name="room-pref"
    ),
    re_path(
        r"visio-preference/(?P<tutor>\w{1,8})?(/?P<link_id>\d{1,8})?/",
        views.visio_preference,
        name="visio-pref",
    ),
    path("preferences/", views.user_preferences, name="preferences"),
    path("semaine-type/", views.stype, name="stype"),
    path("aide/", views.aide, name="aide"),
    path("decale/", views.decale, name="decale"),
    path("contact/", views.contact, name="contact-blank"),
    path("contact/<str:tutor>/", views.contact, name="contact"),
    path(
        "module_description/", views.module_description, name="module_description-blank"
    ),
    path(
        "module_description/<str:module>/",
        views.module_description,
        name="module_description",
    ),
    path("", views.edt, name="edt-blank"),
    path("<yyyy:year>/<int:week>/", views.edt, name="edt"),
    path("tv/", views.edt_light, name="edt-light-blank"),
    path("tv/<yyyy:year>/<int:week>/", views.edt_light, name="edt-light"),
    path("modules/", views.all_modules_with_desc, name="modules"),
    # Send Email to teacher when student want modify schedule
    path("email-modif/", views.send_email_proposal, name="email-proposal"),
    path("roomreservation/", views.room_reservation, name="roomreservation"),
    # exchanges with the db via django
    # ---------------------------------
    # from db to screen
    path(
        "fetch_course_default_week/<str:train_prog>/<str:course_type>/",
        views.fetch_course_default_week,
        name="fetch_course_dweek",
    ),
    path(
        "fetch_room_default_week/<str:room>/",
        views.fetch_room_default_week,
        name="fetch_room_dweek",
    ),
    path("fetch_decale/", views.fetch_decale, name="fetch_decale"),
    path("fetch_groups/", views.fetch_groups, name="fetch_groups"),
    path("fetch_rooms/", views.fetch_rooms, name="fetch_rooms"),
    path("fetch_flat_rooms/", views.fetch_flat_rooms, name="fetch_flat_rooms"),
    path("fetch_constraints/", views.fetch_constraints, name="fetch_constraints"),
    path("fetch_course_types/", views.fetch_course_types, name="fetch_course_types"),
    path(
        "fetch_training_programmes/",
        views.fetch_training_programmes,
        name="fetch_training_programmes",
    ),
    path("fetch_all_tutors/", views.fetch_all_tutors, name="fetch_all_tutors"),
    path("fetch_all_versions/", views.fetch_all_versions, name="fetch_all_versions"),
    path("fetch_departments", views.fetch_departments, name="fetch_departments"),
    path(
        "fetch_shared_rooms/<yyyy:year>/<int:week>/",
        views.fetch_shared_rooms,
        name="fetch_shared_rooms",
    ),
    path(
        "fetch_perfect_day/<str:username>/",
        views.fetch_perfect_day,
        name="fetch_perfect_day",
    ),
    path(
        "fetch_user_notifications_pref/<str:username>/",
        views.fetch_user_notifications_pref,
        name="fetch_user_notifications_pref",
    ),
    path(
        "fetch_all_modules_with_desc/",
        views.fetch_all_modules_with_desc,
        name="fetch_all_modules_with_desc",
    ),
    path(
        "fetch_group_preferred_links/",
        views.fetch_group_preferred_links,
        name="fetch_group_preferred_links",
    ),
    # from screen to db
    path(
        "change_user_pref/<yyyy:year>/<int:week>/<str:username>/",
        views.user_preferences_changes,
        name="user_pref_changes",
    ),
    path(
        "change_course_pref/<yyyy:year>/<int:week>/<str:train_prog>/"
        "<str:course_type>/",
        views.course_preferences_changes,
        name="course_pref_changes",
    ),
    path(
        "change_room_pref/<yyyy:year>/<int:week>/<str:room>/",
        views.room_preferences_changes,
        name="room_pref_changes",
    ),
    path("change_decale/", views.decale_changes, name="decale_changes"),
    path(
        "change_perfect_day/<str:username>/",
        views.user_perfect_day_changes,
        name="user_perfect_day_changes",
    ),
    path(
        "change_user_notifications_pref/<str:username>/",
        views.user_notifications_pref_changes,
        name="user_notifications_pref_changes",
    ),
    path(
        "change_user_themes_pref/<str:username>/",
        views.user_themes_pref_changes,
        name="user_themes_pref_changes",
    ),
    path(
        "change_room_pref_per_tutor/<str:tutor>/",
        views.room_preferences_changes_per_tutor,
        name="room_pref_changes_per_tutor",
    ),
    # predefined
    # ------------
    # deprecated
    # ----------
    re_path(
        r"^fetch_bknews/(?P<year>\d+)/(?P<week>\d+)/$",
        views.fetch_bknews,
        name="fetch_bknews",
    ),
    re_path(
        r"^fetch_unavailable_rooms/(?P<year>\d+)/(?P<week>\d+)/$",
        views.fetch_unavailable_rooms,
        name="fetch_unavailable_rooms",
    ),
    path(
        "fetch_tutor_courses/<int:year>/<int:week>/<str:tutor>/",
        views.fetch_tutor_courses,
        name="fetch_tutor_courses",
    ),
    path(
        "fetch_extra_sched/<int:year>/<int:week>/",
        views.fetch_extra_sched,
        name="fetch_extra_sched",
    ),
    re_path(
        r"^fetch_module/(?P<year>\d+)/(?P<week>\d+)/$",
        views.fetch_module,
        name="fetch_module",
    ),
    re_path(
        r"^fetch_tutors/(?P<year>\d+)/(?P<week>\d+)/$",
        views.fetch_tutor,
        name="fetch_tutor",
    ),
]

# https://pypi.python.org/pypi/django-live-log
# https://github.com/abdullatheef/django_live_log

back/flopedt-django/flopeditor/urls.py
# -*- coding: utf-8 -*-
"""
Python versions: Python 3.6

This file is part of the FlOpEDT/FlOpScheduler project.
Copyright (c) 2017
Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public
License along with this program. If not, see
<http://www.gnu.org/licenses/>.

You can be released from the requirements of the license by purchasing
a commercial license. Buying such a license is mandatory as soon as
you develop activities involving the FlOpEDT/FlOpScheduler software
without disclosing the source code of your own applications.


This module is used to declare the urls related to flop!EDITOR, an app used
to manage a department statistics for FlOpEDT.
"""

from django.urls import path

from .configuration import import_views

from . import crud, views

app_name = "flopeditor"

urlpatterns = [
    # directly reachable by users
    # ---------------------------
    path("", views.home, name="flopeditor-home"),
    path("flopeditor-help/", views.flopeditor_help, name="flopeditor-help"),
    path(
        "<slug:department_abbrev>/",
        views.department_default,
        name="flopeditor-department-default",
    ),
    path(
        "<slug:department_abbrev>/salles",
        views.department_rooms,
        name="flopeditor-department-rooms",
    ),
    path(
        "<slug:department_abbrev>/intervenants",
        views.department_tutors,
        name="flopeditor-department-tutors",
    ),
    path(
        "<slug:department_abbrev>/categories-de-salles",
        views.department_room_types,
        name="flopeditor-department-room-types",
    ),
    path(
        "<slug:department_abbrev>/attributs-de-salles",
        views.department_room_attributes,
        name="flopeditor-department-room-attributes",
    ),
    path(
        "<slug:department_abbrev>/groupes-structuraux",
        views.department_student_structural_groups,
        name="flopeditor-department-student-structural-groups",
    ),
    path(
        "<slug:department_abbrev>/groupes-transversaux",
        views.department_student_transversal_groups,
        name="flopeditor-department-student-transversal-groups",
    ),
    path(
        "<slug:department_abbrev>/natures",
        views.department_student_group_types,
        name="flopeditor-department-student-group-types",
    ),
    path(
        "<slug:department_abbrev>/promos",
        views.department_training_programmes,
        name="flopeditor-department-training-programmes",
    ),
    path(
        "<slug:department_abbrev>/etudiants",
        views.department_students,
        name="flopeditor-department-students",
    ),
    path(
        "<slug:department_abbrev>/modules",
        views.department_modules,
        name="flopeditor-department-modules",
    ),
    path(
        "<slug:department_abbrev>/types-de-cours",
        views.department_course_types,
        name="flopeditor-department-course-types",
    ),
    path(
        "<slug:department_abbrev>/contraintes-de-debut",
        views.department_course_start_times_constraints,
        name="flopeditor-department-course-start-times-constraints",
    ),
    path(
        "<slug:department_abbrev>/semestres",
        views.department_periods,
        name="flopeditor-department-periods",
    ),
    path(
        "<slug:department_abbrev>/parameters",
        views.department_parameters,
        name="flopeditor-department-parameters",
    ),
    path(
        "<slug:department_abbrev>/parameters/edit",
        views.department_parameters_edit,
        name="flopeditor-department-parameters-edit",
    ),
    path(
        "<slug:department_abbrev>/delete",
        views.department_delete,
        name="flopeditor-department-delete",
    ),
    # exchanges with the db via django
    # --------------------------------
    path(
        "ajax/create-department",
        views.ajax_create_department,
        name="flopeditor-ajax-create-department",
    ),
    path(
        "ajax/update-department",
        views.ajax_update_department,
        name="flopeditor-ajax-update-department",
    ),
    path(
        "ajax/parameters-edit/<slug:department_abbrev>",
        views.ajax_edit_parameters,
        name="flopeditor-ajax-edit-department-parameters",
    ),
    path(
        "ajax/update-profil",
        views.ajax_update_profil,
        name="flopeditor-ajax-update-profil",
    ),
    # exchanges with the CRUD
    # --------------------------------
    path(
        "<slug:department_abbrev>/crud/rooms",
        crud.crud_rooms,
        name="flopeditor-crud-rooms",
    ),
    path(
        "<slug:department_abbrev>/crud/tutors",
        crud.crud_tutors,
        name="flopeditor-crud-tutors",
    ),
    path(
        "<slug:department_abbrev>/crud/room_types",
        crud.crud_room_types,
        name="flopeditor-crud-room-types",
    ),
    path(
        "<slug:department_abbrev>/crud/room_attributes",
        crud.crud_room_attributes,
        name="flopeditor-crud-room-attributes",
    ),
    path(
        "<slug:department_abbrev>/crud/group_type",
        crud.crud_student_group_type,
        name="flopeditor-crud-student-group-type",
    ),
    path(
        "<slug:department_abbrev>/crud/student_structural_group",
        crud.crud_student_structural_group,
        name="flopeditor-crud-student-structural-group",
    ),
    path(
        "<slug:department_abbrev>/crud/student_transversal_group",
        crud.crud_student_transversal_group,
        name="flopeditor-crud-student-transversal-group",
    ),
    path(
        "<slug:department_abbrev>/crud/students",
        crud.crud_students,
        name="flopeditor-crud-students",
    ),
    path(
        "<slug:department_abbrev>/crud/modules",
        crud.crud_module,
        name="flopeditor-crud-modules",
    ),
    path(
        "<slug:department_abbrev>/crud/training_programmes",
        crud.crud_training_programmes,
        name="flopeditor-crud-training-programmes",
    ),
    path(
        "<slug:department_abbrev>/crud/courses",
        crud.crud_course,
        name="flopeditor-crud-courses",
    ),
    path(
        "<slug:department_abbrev>/crud/start_times_constraints",
        crud.crud_course_start_times_constraints,
        name="flopeditor-crud-start-times-constraints",
    ),
    path(
        "<slug:department_abbrev>/crud/periods",
        crud.crud_periods,
        name="flopeditor-crud-periods",
    ),
    path(
        "<slug:department_abbrev>/xls_import",
        import_views.configuration,
        name="flopeditor-xls-import",
    ),
    path(
        "<slug:department_abbrev>/upload_config", import_views.import_config_file, name="ul_config"
    ),
    path(
        "<slug:department_abbrev>/upload_planif", import_views.import_planif_file, name="ul_planif"
    ),
    path(
        "<slug:department_abbrev>/download_config", import_views.get_config_file, name="dl_config"
    ),
    path(
        "<slug:department_abbrev>/download_planif", import_views.get_planif_file, name="dl_planif"
    ),
    path(
        "<slug:department_abbrev>/mk_and_dl_blank_planif",
        import_views.mk_and_dl_planif,
        {"with_courses": False},
        name="mk_and_dl_blank_planif",
    ),
    path(
        "<slug:department_abbrev>/mk_and_dl_fullfilled_planif",
        import_views.mk_and_dl_planif,
        {"with_courses": True},
        name="mk_and_dl_fullfilled_planif",
    ),
    path(
        "<slug:department_abbrev>/mk_and_dl_fullfilled_database_file",
        import_views.mk_and_dl_database_file,
        name="mk_and_dl_fullfilled_database_file",
    ),
]

back/flopedt-django/flopeditor/templates/flopeditor/configuration.html
{% extends "flopeditor/base.html" %}
{% load static %}
{% load i18n %}

{% block nav-classes-import %} active {% endblock %}

{% block content-flopeditor %}
    <script>
        let department = "{{ department|safe }}";
        let list_departments = {{ list_departments|safe }};
        let training_periods = {{ training_periods|safe }};
        let scheduling_periods = {{ scheduling_periods|safe }};
        let current_year = {{ current_year }};
        let next_year = {{current_year|add:"1"}};
        $(() => {
            $("form:not([id])").submit(function() {
                const submitBtn = $('[type=submit]', this).attr('disabled', 'true')
                $.get($(this).attr('action'), $(this).serialize(), () => submitBtn.removeAttr('disabled'), 'text')
                return true
            })
        })
    </script>
    <script type="text/javascript" src="{% static 'flopeditor/js/configuration_vars.js' %}"></script>
    <h3>{% trans "Step 1 - Database configuration" %}</h3>
    <div class="step">
        <h4>{% trans "Configuration file canvas" %}</h4>
        <p>{% trans "Download and then complete the file below." %}</p>
            {% trans "Click to download the empty configuration file" %}
            <a href="{% url "flopeditor:dl_config" department.abbrev %}"><button id="btn_config_1">{% trans "Download"%}</button></a>
        <br/>
        <br/>
        {% trans "Click to make and download a new fullfilled database file" %}
        <a href="{% url "flopeditor:mk_and_dl_fullfilled_database_file" department.abbrev %}"><button id="btn_dl_database_file">{% trans "Make_and_download"%}</button></a>
    </div>

    <div class="step">
        <h3>{% trans "Configuration file completed" %}</h3>
        <p>{% trans "Upload the completed configuration file." %} ({% trans "Only xlsx format is accepted."%})</p>
        <form action="{% url "flopeditor:ul_config" department.abbrev %}" method="post" enctype="multipart/form-data" id="config">
                {% csrf_token %}
            <fieldset>
                <div id="depart_choice"></div>
                {{ form_config }}
                <input type="submit" value={% trans "Import" %}>
            </fieldset>
        </form>

        <div id="error_config">
          <h4>{% trans "Verdict :"%}</h4>
          <p></p>
        </div>
    </div>

        <br/>
        <br/>
        <br/>

    <h3>{% trans "Step 2 - Plan the lessons " %}</h3>
    <div class="step">
    <h4>{% trans "Template for the planning file" %}</h4>
        {% trans "Click to download the current planning file outline" %}
        <a href="{% url "flopeditor:dl_planif" department.abbrev %}"><button id="btn_dl_current_planif">{% trans "Download"%}</button></a>

        <br/>
        {% trans "Click to make and download a new blank planning file outline" %}
        {% trans " (it may last several minuts)." %}
        <a href="{% url "flopeditor:mk_and_dl_blank_planif" department.abbrev %}"><button id="btn_dl_new_planif">{% trans "Make_and_download" %}</button></a>

        <br/>
        {% trans "Click to make and download a new fullfilled planning file outline" %}
        {% trans " (it may last several minuts)." %}
        <a href="{% url "flopeditor:mk_and_dl_fullfilled_planif" department.abbrev %}"><button id="btn_fullfilled_planif">{% trans "Make_and_download" %}</button></a>

    </div>
    <br/>
    <br/>

    <div class="step">
        <fieldset>
            <legend> <h4>{% trans "Completed planning file" %}</h4> </legend>
            <p>{% trans "Upload the completed planning file." %} ({% trans "Only xlsx format is accepted." %})</p>
            <form action="{% url "flopeditor:ul_planif" department.abbrev %}"
                  method="post"
                  enctype="multipart/form-data"
                  id="planif">
                {% csrf_token %}
                {{ form_planif }}
                </br>
                </br>
                    <div id="choose_training_periods">
                        <input type="checkbox" id="choose_training_periods" name="choose_training_periods"/>
                            <label for="choose_training_periods">{% trans "Only for training periods " %}
                                <select multiple name="training_periods" id="dropdown_training_periods"> </select>
                            </label>
                    </div>
                </br>
                </br>
                <div id="choose_scheduling_periods">
                    <input type="checkbox" id="choose_scheduling_periods" name="choose_scheduling_periods"/>
                        <label for="choose_scheduling_periods">{% trans "Only for scheduling periods " %}
                            <select multiple name="scheduling_periods" id="dropdown_scheduling_periods"> </select>
                        </label>
                </div>
                </br>
                <input type="checkbox" id="stabilize" name="stabilize"/>
                <label for="stabilize">{% trans "Stabilization ?" %}</label>
                </br></br>
                <input type="checkbox" id="assign_colors" name="assign_colors"/>
                <label for="assign_colors">{% trans "(Re)assign colors ?" %}</label>
                </br></br>
                <input type="submit"
                       id="submitImport"
                       onclick="return confirm(
                           confirm_text.intro + '\n\n' +
                           translated_department + '{{ department.abbrev }}' + '\n' +
                           translated_training_periods + confirm_text.training_periods + '\n' +
                           translated_scheduling_periods + confirm_text.scheduling_periods)"
                       value={% trans "Import" %}>
            </form>
        </fieldset>
        <div id="error_planif">
          <h4>{% trans "Verdict :" %}</h4>
          <p></p>
        </div>
    </div>

<script type="text/javascript" src="{% static 'flopeditor/js/configuration.js' %}"></script>

{% endblock %}

back/flopedt-django/flopeditor/templates/flopeditor/student_transversal_groups.html
{% extends "flopeditor/student_group_types.html" %}
{% load static %}

{% block card-nav-classes-student-group-types %}{% endblock %}
{% block card-nav-classes-student-transversal-groups %}active{% endblock %}

{% block crud_js_url %}{% url 'flopeditor:flopeditor-crud-student-transversal-group' department_abbrev=department.abbrev %}{% endblock %}