back/flopedt-django/api/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.
from django.urls import path
from rest_framework import routers

from api.base import views

routerBase = routers.SimpleRouter()

# routerBase.register(r'studentspreferences', views.StudentPreferencesViewSet, basename="students")
# routerBase.register(r'groupspreferences', views.GroupPreferencesViewSet)

# routerBase.register(r'departments', views.DepartmentViewSet)
routerBase.register(
    r"trainingprogram/name",
    views.TrainingProgrammeNameViewSet,
    basename="trainingprogramme-name",
)
# routerBase.register(r'trainingprogram', views.TrainingProgrammeViewSet)
# routerBase.register(r'holidays', views.HolidaysViewSet)
# routerBase.register(r'traininghalfdays', views.TrainingHalfDaysViewSet)
routerBase.register(r"trainingperiods", views.TrainingPeriodsViewSet, basename="trainingperiods")
routerBase.register(r"timesettings", views.TimeGeneralSettingsViewSet, basename="timesettings")
routerBase.register(r"weeks", views.SchedulingPeriodsViewSet, basename="weeks")
routerBase.register(r"periods", views.SchedulingPeriodsViewSet, basename="periods")
# routerBase.register(r'timetableversions', views.TimetableVersionsViewSet)
# routerBase.register(r'coursemodifications', views.CourseModificationsViewSet)
# routerBase.register(r'tutorcosts', views.TutorCostsViewSet)
# routerBase.register(r'groupcosts', views.GroupCostsViewSet)
# routerBase.register(r'CourseStartTimeFilter', views.GroupFreeHalfDaysViewSet)
# routerBase.register(r'dependencies', views.DependenciesViewSet)
# routerBase.register(r'regens', views.RegensViewSet)
# routerBase.register(r'login', views.LoginView, basename="login")
# routerBase.register(r'logout', views.LogoutView, basename="logout")
url_base_patterns = [
    path(r"contact", views.ContactView.as_view(), name="contactMail"),
]

url_base_patterns += routerBase.urls

back/flopedt-django/api/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework import routers

import api.base.views as views_base
import api.fetch.views as views_fetch
from api import views
from api.base.courses.urls import routerCourses
from api.base.groups.urls import routerGroups
from api.base.rooms.urls import routerRooms
from api.base.urls import url_base_patterns
from api.fetch.urls import routerFetch
from api.people.urls import url_user_patterns
from api.TTapp.urls import routerTTapp
from api.celcat.urls import routerCelcat

# V1...
from api.v1.urls import url_V1_patterns

#####################################
# URLS based on django applications #
#####################################

app_name = "api"

routerDisplayweb = routers.SimpleRouter()

routerDisplayweb.register(r"breakingnews", views.BreakingNewsViewSet)
routerDisplayweb.register(r"moduledisplays", views.ModuleDisplaysViewSet)
routerDisplayweb.register(
    r"trainingprogrammedisplays", views.TrainingProgrammeDisplaysViewSet
)
routerDisplayweb.register(r"groupdisplays", views.GroupDisplaysViewSet)

######################
# User friendly URLS #
######################

routerExtra = routers.SimpleRouter()

routerExtra.register("bknews", views_fetch.BKNewsViewSet, basename="bknews")
routerExtra.register("quote/random", views.RandomQuoteViewSet, basename="random-quote")
routerExtra.register("quote", views.QuoteViewSet)
routerExtra.register("week-infos", views.WeekInfoViewSet, basename="week-infos")

################
# SWAGGER VIEW #
################


urlpatterns = [
    path("", views_base.LoginView.as_view(), name="api_root"),
    path("logout/", views_base.LogoutView.as_view()),
    path(
        "backoffice/", login_required(TemplateView.as_view(template_name="logout.html"))
    ),
    path("base/", include((url_base_patterns, "api"), namespace="base")),
    path("user/", include((url_user_patterns, "api"), namespace="people")),
    # path("display/", include(routerDisplayweb.urls)),
    path("ttapp/", include((routerTTapp.urls, "api"), namespace="ttapp")),
    path("fetch/", include((routerFetch.urls, "api"), namespace="fetch")),
    # path("rest-auth/", include("dj_rest_auth.urls")),
    # path("api-token-auth/", obtain_auth_token, name="api_token_auth"),
    path("rooms/", include((routerRooms.urls, "api"), namespace="rooms")),
    path("courses/", include((routerCourses.urls, "api"), namespace="course")),
    path("groups/", include((routerGroups.urls, "api"), namespace="groups")),
    # path("extra/", include((routerExtra.urls, "api"), namespace="extra")),
    # path(
    #     "roomreservations/",
    #     include((routerRoomReservation.urls, "api"), namespace="roomreservations"),
    # ),
    path("v1/", include((url_V1_patterns, "api"), namespace="V1")),
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "doc/",
        SpectacularSwaggerView.as_view(url_name="api:schema"),
        name="swagger-ui",
    ),
    path("celcat/", include((routerCelcat.urls, "api"), namespace="celcat")),
]

back/flopedt-django/api/v1/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.
from django.urls import include, path

from api.v1.base.courses.urls import routerCourse
from api.v1.base.modification.urls import routerModification
from api.v1.base.timing.urls import routerTiming

url_base_patterns = [
    path("courses/", include((routerCourse.urls, "api"), namespace="course")),
    path(
        "modification/",
        include((routerModification.urls, "api"), namespace="modifications"),
    ),
    path("timing/", include((routerTiming.urls, "api"), namespace="timing")),
]

back/flopedt-django/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.urls import path, re_path

from . import views

app_name = "base"

urlpatterns = [
    # favicon
    # ----------------------------
    re_path(views.FAV_REGEXP, views.favicon, name="favicon"),
    # directly reachable by users
    # ----------------------------
    re_path(
        r"room-preference/(?P<tutor>\w{2,8})?/", views.room_preference, name="room-pref"
    ),
    re_path(
        r"visio-preference/(?P<tutor>\w{1,8})?(/?P<link_id>\d{1,8})?/",
        views.visio_preference,
        name="visio-pref",
    ),
    path("preferences/", views.user_preferences, name="preferences"),
    path("semaine-type/", views.stype, name="stype"),
    path("aide/", views.aide, name="aide"),
    path("decale/", views.decale, name="decale"),
    path("contact/", views.contact, name="contact-blank"),
    path("contact/<str:tutor>/", views.contact, name="contact"),
    path(
        "module_description/", views.module_description, name="module_description-blank"
    ),
    path(
        "module_description/<str:module>/",
        views.module_description,
        name="module_description",
    ),
    path("", views.edt, name="edt-blank"),
    path("<yyyy:year>/<int:week>/", views.edt, name="edt"),
    path("tv/", views.edt_light, name="edt-light-blank"),
    path("tv/<yyyy:year>/<int:week>/", views.edt_light, name="edt-light"),
    path("modules/", views.all_modules_with_desc, name="modules"),
    # Send Email to teacher when student want modify schedule
    path("email-modif/", views.send_email_proposal, name="email-proposal"),
    path("roomreservation/", views.room_reservation, name="roomreservation"),
    # exchanges with the db via django
    # ---------------------------------
    # from db to screen
    path(
        "fetch_course_default_week/<str:train_prog>/<str:course_type>/",
        views.fetch_course_default_week,
        name="fetch_course_dweek",
    ),
    path(
        "fetch_room_default_week/<str:room>/",
        views.fetch_room_default_week,
        name="fetch_room_dweek",
    ),
    path("fetch_decale/", views.fetch_decale, name="fetch_decale"),
    path("fetch_groups/", views.fetch_groups, name="fetch_groups"),
    path("fetch_rooms/", views.fetch_rooms, name="fetch_rooms"),
    path("fetch_flat_rooms/", views.fetch_flat_rooms, name="fetch_flat_rooms"),
    path("fetch_constraints/", views.fetch_constraints, name="fetch_constraints"),
    path("fetch_course_types/", views.fetch_course_types, name="fetch_course_types"),
    path(
        "fetch_training_programmes/",
        views.fetch_training_programmes,
        name="fetch_training_programmes",
    ),
    path("fetch_all_tutors/", views.fetch_all_tutors, name="fetch_all_tutors"),
    path("fetch_all_versions/", views.fetch_all_versions, name="fetch_all_versions"),
    path("fetch_departments", views.fetch_departments, name="fetch_departments"),
    path(
        "fetch_shared_rooms/<yyyy:year>/<int:week>/",
        views.fetch_shared_rooms,
        name="fetch_shared_rooms",
    ),
    path(
        "fetch_perfect_day/<str:username>/",
        views.fetch_perfect_day,
        name="fetch_perfect_day",
    ),
    path(
        "fetch_user_notifications_pref/<str:username>/",
        views.fetch_user_notifications_pref,
        name="fetch_user_notifications_pref",
    ),
    path(
        "fetch_all_modules_with_desc/",
        views.fetch_all_modules_with_desc,
        name="fetch_all_modules_with_desc",
    ),
    path(
        "fetch_group_preferred_links/",
        views.fetch_group_preferred_links,
        name="fetch_group_preferred_links",
    ),
    # from screen to db
    path(
        "change_user_pref/<yyyy:year>/<int:week>/<str:username>/",
        views.user_preferences_changes,
        name="user_pref_changes",
    ),
    path(
        "change_course_pref/<yyyy:year>/<int:week>/<str:train_prog>/"
        "<str:course_type>/",
        views.course_preferences_changes,
        name="course_pref_changes",
    ),
    path(
        "change_room_pref/<yyyy:year>/<int:week>/<str:room>/",
        views.room_preferences_changes,
        name="room_pref_changes",
    ),
    path("change_decale/", views.decale_changes, name="decale_changes"),
    path(
        "change_perfect_day/<str:username>/",
        views.user_perfect_day_changes,
        name="user_perfect_day_changes",
    ),
    path(
        "change_user_notifications_pref/<str:username>/",
        views.user_notifications_pref_changes,
        name="user_notifications_pref_changes",
    ),
    path(
        "change_user_themes_pref/<str:username>/",
        views.user_themes_pref_changes,
        name="user_themes_pref_changes",
    ),
    path(
        "change_room_pref_per_tutor/<str:tutor>/",
        views.room_preferences_changes_per_tutor,
        name="room_pref_changes_per_tutor",
    ),
    # predefined
    # ------------
    # deprecated
    # ----------
    re_path(
        r"^fetch_bknews/(?P<year>\d+)/(?P<week>\d+)/$",
        views.fetch_bknews,
        name="fetch_bknews",
    ),
    re_path(
        r"^fetch_unavailable_rooms/(?P<year>\d+)/(?P<week>\d+)/$",
        views.fetch_unavailable_rooms,
        name="fetch_unavailable_rooms",
    ),
    path(
        "fetch_tutor_courses/<int:year>/<int:week>/<str:tutor>/",
        views.fetch_tutor_courses,
        name="fetch_tutor_courses",
    ),
    path(
        "fetch_extra_sched/<int:year>/<int:week>/",
        views.fetch_extra_sched,
        name="fetch_extra_sched",
    ),
    re_path(
        r"^fetch_module/(?P<year>\d+)/(?P<week>\d+)/$",
        views.fetch_module,
        name="fetch_module",
    ),
    re_path(
        r"^fetch_tutors/(?P<year>\d+)/(?P<week>\d+)/$",
        views.fetch_tutor,
        name="fetch_tutor",
    ),
]

# https://pypi.python.org/pypi/django-live-log
# https://github.com/abdullatheef/django_live_log

back/flopedt-django/cstmanager/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.urls import path

from cstmanager import views

app_name = "cstmanager"

urlpatterns = [
    path("manager", views.manager, name="cstmanager"),
]

back/flopedt-django/flop_ics/urls.py
from django.urls import path

from flop_ics import views
from flop_ics.feeds import (
    RegenFeed,
    RoomEventFeed,
    StructuralGroupEventFeed,
    TransversalGroupEventFeed,
    TutorEventFeed,
)

app_name = "flop_ics"

urlpatterns = [
    path(r"", views.index, name="index"),
    path(r"tutor/<int:tutor_id>.ics", TutorEventFeed(), name="tutor"),
    path(r"room/<int:room_id>.ics", RoomEventFeed(), name="room"),
    path(
        r"structural_group/<int:group_id>.ics",
        StructuralGroupEventFeed(),
        name="structural_group",
    ),
    path(
        r"transversal_group/<int:group_id>.ics",
        TransversalGroupEventFeed(),
        name="transversal_group",
    ),
    path(r"regen/<int:dep_id>.ics", RegenFeed(), name="regen"),
]

back/flopedt-django/templates/base.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing-->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
<style>
</style>
<link rel="stylesheet" href="{% static 'base/header.css' %}?4" />
<link rel="stylesheet" href="{% static 'TTapp/styles.css' %}" />
<link rel="apple-touch-icon" sizes="180x180" href=" /static/base/img/favicons/apple-touch-icon.png?v=5AeyQYqgW7">
<link rel="icon" type="image/png" sizes="32x32" href=" /static/base/img/favicons/favicon-32x32.png?v=5AeyQYqgW7">
<link rel="icon" type="image/png" sizes="16x16" href=" /static/base/img/favicons/favicon-16x16.png?v=5AeyQYqgW7">
<link rel="manifest" href=" /static/base/img/favicons/site.webmanifest?v=5AeyQYqgW7">
<link rel="mask-icon" href=" /static/base/img/favicons/safari-pinned-tab.svg?v=5AeyQYqgW7" color="#858585">
<link rel="shortcut icon" href=" /static/base/img/favicons/favicon.ico?v=5AeyQYqgW7">
<meta charset="UTF-8">
<meta name="msapplication-TileColor" content="#048c04">
<meta name="theme-color" content="#000000">

<script src="{% url 'javascript-catalog' %}"></script>
{% block jquery %}
<script src="{% static 'base/jquery.min.js' %}"></script>
{% endblock %}
<script src="{% static 'base/d3.v4.min.js' %}"></script>
<script src="{% static 'base/loader.js' %}"></script>
<script>var url_logo = "{% static 'base/logo-clock.svg' %}";</script>
<!-- script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script -->
<title>{% block title %}{% trans "Schedule_title" %}{% endblock %}</title>

{% block css %}
{% endblock %}
{#    Allows to display a theme according to the user's preferences #}
{#    If the user doesn't have a preferred theme yet, no css file will be overloaded#}
{#    The white theme doesn't overload any file#}

{% if request.user.get_theme == "Brume" %}
    <link rel="stylesheet" href="{% static 'base/themes/themeBrume.css' %}"/>
{% elif request.user.get_theme == "Prestige Edition" %}
    <link rel="stylesheet" href="{% static 'base/themes/themePrestige.css' %}"/>
{% elif request.user.get_theme == "SynthWave" %}
    <link rel="stylesheet" href="{% static 'base/themes/themeSynthWave.css' %}"/>
{% elif request.user.get_theme == "Dark" %}
    <link rel="stylesheet" href="{% static 'base/themes/themeDark.css' %}"/>
{% elif request.user.get_theme == "Pink" %}
    <link rel="stylesheet" href="{% static 'base/themes/themePink.css' %}"/>
{% endif %}


</head>
<body>
  {% block loader %}
  <div id="loader" class="loader" style="visibility:hidden;"></div>
  {% endblock %}
  <!--<header>Emplois du temps</header>-->
  {% block full_nav %}
  <nav id="menu-edt">
    <a class="hide_this_link" id="live-logo"  style="padding: 0px 0px 0px 0px; float: left" >
    </a>
    <div id="full_logo">
      <a style="text-decoration: none; font-family: inherit; color: inherit" href="{% url 'index' %}">
          <span id="acro_logo">{% trans "<span id=flopGreen >flop</span>!<span id=EDTRed >Scheduler</span>" %}</span>
      </a>
      {% autoescape off %}
      <span id="head_logo"></span>
      {% endautoescape %}
      <a id="idea_box" target="_blank" href="https://framaforms.org/flopedt-boite-a-idees-1681143369">
          <img src="{% static 'base/img/boite_a_idees_flop_2.png'%}" width="40" alt="idea_box"/>
            BOÎTE A IDEES
      </a>
      <a id="agpl" target="_blank" href="https://framagit.org/flopedt/flopedt">
	      <img src="{% static 'base/agplv3-88x31.png'%}" height="31" width="88" alt="AGPL v.3"/>

      </a>
    </div>

    {% block nav %}
    <ul>
      {% if request.department %}
          {% if request.is_department_admin %}
            <li><a href="#" onclick="openNav()">☰</a></li>
          {% endif %}
            <li><a href="{% url 'base:edt-blank' department %}">{% trans 'Schedule_banner' %}</a></li>
          {% if request.has_department_perm %}
            <li><a href="{% url 'base:decale' department %}">{% trans 'Move/Cancel' %}</a></li>
          {% endif %}
          <li><a href="{% url 'base:preferences' department %}">{% trans 'Preferences' %}</a></li>
          <li><a href="{% url 'flop_ics:index' department %}">{% trans 'iCal' %}</a></li>
          <li><a href="{% url 'base:aide' department %}">{% trans 'Help' %}</a></li>
          <li><a href="{% url 'base:contact-blank' department %}">{% trans 'Messages' %}</a></li>
          <li><a href="{% url 'base:modules' department %}">{% trans 'Modules' %}</a></li>
          <li><a href="{% url 'base:roomreservation' department %}">{% trans 'Reservations'%}</a></li>
          {% if request.is_department_admin %}
              <li><a href="{% url 'cstmanager:cstmanager' department %}">{% trans 'Constraints'%}</a></li>
              <li><a href="{% url 'solve_board:main_board' department %}">{% trans 'Generate' %}</a></li>
              <li><a href="{% url 'flopeditor:flopeditor-department-default' department %}">{% trans 'flop!EDITOR' %}</a></li>
              <li><a href="{% url 'configuration:configuration' %}">{% trans 'Import'%}</a></li>
              <li><a href="{% url 'admin:index' %}">{% trans 'Admin'%}</a></li>
          {% endif %}
      {% endif %}
      <li style="float:right">
	{% if user.is_authenticated %}
	{% if request.department %}
	<a href="{% url 'people:logout' %}?next={% url 'base:edt-blank' department %}">{% trans 'Sign out' %}</a>
	{% elif not 'accounts' in request.path %}
	<a href="{% url 'people:logout' %}?next={{request.path}}">{% trans 'Sign out' %}</a>
	{% else %}
	<a href="{% url 'people:logout' %}">{% trans "Sign out" %}</a>
	{% endif %}
	{% else %}
	<a href="{% url 'people:login' %}?next={{request.path}}" id='sign_in'>{% trans 'Sign in' %}</a>
	{% endif %}
      </li>
      <li style="float:right">{% if user.is_authenticated %}
	<a href="{% url 'people:change_redirect' %}">{% trans 'Signed in as ' %} {{ user.username }}</a> {% endif %}
      </li>
    </ul>
    {% endblock %}
  </nav>
  {% endblock %}
  <section id="content">
    {% block content %}{% endblock %}
    <div id="side_panel" class="sidebar">
      <a href="javascript:void(0)" class="btn_panel" onclick="closeNav()">×</a>
      {% block side_panel %} {% endblock %}
    </div>
  </section>

  {% block logo %}
  <script src="{% static 'base/logo.js' %}"></script>
  {% endblock %}
  {% block javascript %}
  {% endblock %}
</body>
</html>

back/flopedt-django/templates/skeleton.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing-->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% block full_nav %}{% endblock %}
{% block logo %}{% endblock %}