back/flopedt-django/TTapp/urls.py
from django.urls import path

import TTapp.views

app_name = "TTapp"

urlpatterns = [
    path(
        "side_panel/<int:period_id>/",
        TTapp.views.available_major_versions,
        name="available_major_versions",
    ),
    path(
        "check_swap/<int:period_id>/<int:major>/",
        TTapp.views.check_swap,
        name="check_swap",
    ),
    path("swap/<int:period_id>/<int:major>/", TTapp.views.swap, name="swap"),
    path(
        "delete_version/<int:period_id>/<int:major>/",
        TTapp.views.delete_version,
        name="delete_version",
    ),
    path(
        "duplicate_version/<int:period_id>/<int:major>/",
        TTapp.views.duplicate_version,
        name="duplicate_version",
    ),
    path(
        "delete_all_unused_versions/<int:period_id>/",
        TTapp.views.delete_all_unused_versions,
        name="delete_all_unused_versions",
    ),
    path(
        "reassign_rooms/<int:period_id>/<int:major>/",
        TTapp.views.reassign_rooms,
        name="reassign_rooms",
    ),
    path(
        "duplicate_in_other_periods/<int:period_id>/<int:major>/",
        TTapp.views.duplicate_in_other_periods,
        name="duplicate_in_other_periods",
    ),
    path("fetch_group_lunch/", TTapp.views.fetch_group_lunch, name="fetch_group_lunch"),
]

back/flopedt-django/api/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.
from django.urls import path
from rest_framework import routers

from api.base import views

routerBase = routers.SimpleRouter()

# routerBase.register(r'studentspreferences', views.StudentPreferencesViewSet, basename="students")
# routerBase.register(r'groupspreferences', views.GroupPreferencesViewSet)

# routerBase.register(r'departments', views.DepartmentViewSet)
routerBase.register(
    r"trainingprogram/name",
    views.TrainingProgrammeNameViewSet,
    basename="trainingprogramme-name",
)
# routerBase.register(r'trainingprogram', views.TrainingProgrammeViewSet)
# routerBase.register(r'holidays', views.HolidaysViewSet)
# routerBase.register(r'traininghalfdays', views.TrainingHalfDaysViewSet)
routerBase.register(r"trainingperiods", views.TrainingPeriodsViewSet, basename="trainingperiods")
routerBase.register(r"timesettings", views.TimeGeneralSettingsViewSet, basename="timesettings")
routerBase.register(r"weeks", views.SchedulingPeriodsViewSet, basename="weeks")
routerBase.register(r"periods", views.SchedulingPeriodsViewSet, basename="periods")
# routerBase.register(r'timetableversions', views.TimetableVersionsViewSet)
# routerBase.register(r'coursemodifications', views.CourseModificationsViewSet)
# routerBase.register(r'tutorcosts', views.TutorCostsViewSet)
# routerBase.register(r'groupcosts', views.GroupCostsViewSet)
# routerBase.register(r'CourseStartTimeFilter', views.GroupFreeHalfDaysViewSet)
# routerBase.register(r'dependencies', views.DependenciesViewSet)
# routerBase.register(r'regens', views.RegensViewSet)
# routerBase.register(r'login', views.LoginView, basename="login")
# routerBase.register(r'logout', views.LogoutView, basename="logout")
url_base_patterns = [
    path(r"contact", views.ContactView.as_view(), name="contactMail"),
]

url_base_patterns += routerBase.urls

back/flopedt-django/api/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework import routers

import api.base.views as views_base
import api.fetch.views as views_fetch
from api import views
from api.base.courses.urls import routerCourses
from api.base.groups.urls import routerGroups
from api.base.rooms.urls import routerRooms
from api.base.urls import url_base_patterns
from api.fetch.urls import routerFetch
from api.people.urls import url_user_patterns
from api.TTapp.urls import routerTTapp
from api.celcat.urls import routerCelcat

# V1...
from api.v1.urls import url_V1_patterns

#####################################
# URLS based on django applications #
#####################################

app_name = "api"

routerDisplayweb = routers.SimpleRouter()

routerDisplayweb.register(r"breakingnews", views.BreakingNewsViewSet)
routerDisplayweb.register(r"moduledisplays", views.ModuleDisplaysViewSet)
routerDisplayweb.register(
    r"trainingprogrammedisplays", views.TrainingProgrammeDisplaysViewSet
)
routerDisplayweb.register(r"groupdisplays", views.GroupDisplaysViewSet)

######################
# User friendly URLS #
######################

routerExtra = routers.SimpleRouter()

routerExtra.register("bknews", views_fetch.BKNewsViewSet, basename="bknews")
routerExtra.register("quote/random", views.RandomQuoteViewSet, basename="random-quote")
routerExtra.register("quote", views.QuoteViewSet)
routerExtra.register("week-infos", views.WeekInfoViewSet, basename="week-infos")

################
# SWAGGER VIEW #
################


urlpatterns = [
    path("", views_base.LoginView.as_view(), name="api_root"),
    path("logout/", views_base.LogoutView.as_view()),
    path(
        "backoffice/", login_required(TemplateView.as_view(template_name="logout.html"))
    ),
    path("base/", include((url_base_patterns, "api"), namespace="base")),
    path("user/", include((url_user_patterns, "api"), namespace="people")),
    # path("display/", include(routerDisplayweb.urls)),
    path("ttapp/", include((routerTTapp.urls, "api"), namespace="ttapp")),
    path("fetch/", include((routerFetch.urls, "api"), namespace="fetch")),
    # path("rest-auth/", include("dj_rest_auth.urls")),
    # path("api-token-auth/", obtain_auth_token, name="api_token_auth"),
    path("rooms/", include((routerRooms.urls, "api"), namespace="rooms")),
    path("courses/", include((routerCourses.urls, "api"), namespace="course")),
    path("groups/", include((routerGroups.urls, "api"), namespace="groups")),
    # path("extra/", include((routerExtra.urls, "api"), namespace="extra")),
    # path(
    #     "roomreservations/",
    #     include((routerRoomReservation.urls, "api"), namespace="roomreservations"),
    # ),
    path("v1/", include((url_V1_patterns, "api"), namespace="V1")),
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "doc/",
        SpectacularSwaggerView.as_view(url_name="api:schema"),
        name="swagger-ui",
    ),
    path("celcat/", include((routerCelcat.urls, "api"), namespace="celcat")),
]

back/flopedt-django/api/v1/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.
from django.urls import include, path

from api.v1.base.courses.urls import routerCourse
from api.v1.base.modification.urls import routerModification
from api.v1.base.timing.urls import routerTiming

url_base_patterns = [
    path("courses/", include((routerCourse.urls, "api"), namespace="course")),
    path(
        "modification/",
        include((routerModification.urls, "api"), namespace="modifications"),
    ),
    path("timing/", include((routerTiming.urls, "api"), namespace="timing")),
]

back/flopedt-django/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.urls import path, re_path

from . import views

app_name = "base"

urlpatterns = [
    # favicon
    # ----------------------------
    re_path(views.FAV_REGEXP, views.favicon, name="favicon"),
    # directly reachable by users
    # ----------------------------
    re_path(
        r"room-preference/(?P<tutor>\w{2,8})?/", views.room_preference, name="room-pref"
    ),
    re_path(
        r"visio-preference/(?P<tutor>\w{1,8})?(/?P<link_id>\d{1,8})?/",
        views.visio_preference,
        name="visio-pref",
    ),
    path("preferences/", views.user_preferences, name="preferences"),
    path("semaine-type/", views.stype, name="stype"),
    path("aide/", views.aide, name="aide"),
    path("decale/", views.decale, name="decale"),
    path("contact/", views.contact, name="contact-blank"),
    path("contact/<str:tutor>/", views.contact, name="contact"),
    path(
        "module_description/", views.module_description, name="module_description-blank"
    ),
    path(
        "module_description/<str:module>/",
        views.module_description,
        name="module_description",
    ),
    path("", views.edt, name="edt-blank"),
    path("<yyyy:year>/<int:week>/", views.edt, name="edt"),
    path("tv/", views.edt_light, name="edt-light-blank"),
    path("tv/<yyyy:year>/<int:week>/", views.edt_light, name="edt-light"),
    path("modules/", views.all_modules_with_desc, name="modules"),
    # Send Email to teacher when student want modify schedule
    path("email-modif/", views.send_email_proposal, name="email-proposal"),
    path("roomreservation/", views.room_reservation, name="roomreservation"),
    # exchanges with the db via django
    # ---------------------------------
    # from db to screen
    path(
        "fetch_course_default_week/<str:train_prog>/<str:course_type>/",
        views.fetch_course_default_week,
        name="fetch_course_dweek",
    ),
    path(
        "fetch_room_default_week/<str:room>/",
        views.fetch_room_default_week,
        name="fetch_room_dweek",
    ),
    path("fetch_decale/", views.fetch_decale, name="fetch_decale"),
    path("fetch_groups/", views.fetch_groups, name="fetch_groups"),
    path("fetch_rooms/", views.fetch_rooms, name="fetch_rooms"),
    path("fetch_flat_rooms/", views.fetch_flat_rooms, name="fetch_flat_rooms"),
    path("fetch_constraints/", views.fetch_constraints, name="fetch_constraints"),
    path("fetch_course_types/", views.fetch_course_types, name="fetch_course_types"),
    path(
        "fetch_training_programmes/",
        views.fetch_training_programmes,
        name="fetch_training_programmes",
    ),
    path("fetch_all_tutors/", views.fetch_all_tutors, name="fetch_all_tutors"),
    path("fetch_all_versions/", views.fetch_all_versions, name="fetch_all_versions"),
    path("fetch_departments", views.fetch_departments, name="fetch_departments"),
    path(
        "fetch_shared_rooms/<yyyy:year>/<int:week>/",
        views.fetch_shared_rooms,
        name="fetch_shared_rooms",
    ),
    path(
        "fetch_perfect_day/<str:username>/",
        views.fetch_perfect_day,
        name="fetch_perfect_day",
    ),
    path(
        "fetch_user_notifications_pref/<str:username>/",
        views.fetch_user_notifications_pref,
        name="fetch_user_notifications_pref",
    ),
    path(
        "fetch_all_modules_with_desc/",
        views.fetch_all_modules_with_desc,
        name="fetch_all_modules_with_desc",
    ),
    path(
        "fetch_group_preferred_links/",
        views.fetch_group_preferred_links,
        name="fetch_group_preferred_links",
    ),
    # from screen to db
    path(
        "change_user_pref/<yyyy:year>/<int:week>/<str:username>/",
        views.user_preferences_changes,
        name="user_pref_changes",
    ),
    path(
        "change_course_pref/<yyyy:year>/<int:week>/<str:train_prog>/"
        "<str:course_type>/",
        views.course_preferences_changes,
        name="course_pref_changes",
    ),
    path(
        "change_room_pref/<yyyy:year>/<int:week>/<str:room>/",
        views.room_preferences_changes,
        name="room_pref_changes",
    ),
    path("change_decale/", views.decale_changes, name="decale_changes"),
    path(
        "change_perfect_day/<str:username>/",
        views.user_perfect_day_changes,
        name="user_perfect_day_changes",
    ),
    path(
        "change_user_notifications_pref/<str:username>/",
        views.user_notifications_pref_changes,
        name="user_notifications_pref_changes",
    ),
    path(
        "change_user_themes_pref/<str:username>/",
        views.user_themes_pref_changes,
        name="user_themes_pref_changes",
    ),
    path(
        "change_room_pref_per_tutor/<str:tutor>/",
        views.room_preferences_changes_per_tutor,
        name="room_pref_changes_per_tutor",
    ),
    # predefined
    # ------------
    # deprecated
    # ----------
    re_path(
        r"^fetch_bknews/(?P<year>\d+)/(?P<week>\d+)/$",
        views.fetch_bknews,
        name="fetch_bknews",
    ),
    re_path(
        r"^fetch_unavailable_rooms/(?P<year>\d+)/(?P<week>\d+)/$",
        views.fetch_unavailable_rooms,
        name="fetch_unavailable_rooms",
    ),
    path(
        "fetch_tutor_courses/<int:year>/<int:week>/<str:tutor>/",
        views.fetch_tutor_courses,
        name="fetch_tutor_courses",
    ),
    path(
        "fetch_extra_sched/<int:year>/<int:week>/",
        views.fetch_extra_sched,
        name="fetch_extra_sched",
    ),
    re_path(
        r"^fetch_module/(?P<year>\d+)/(?P<week>\d+)/$",
        views.fetch_module,
        name="fetch_module",
    ),
    re_path(
        r"^fetch_tutors/(?P<year>\d+)/(?P<week>\d+)/$",
        views.fetch_tutor,
        name="fetch_tutor",
    ),
]

# https://pypi.python.org/pypi/django-live-log
# https://github.com/abdullatheef/django_live_log

back/flopedt-django/flop_ics/urls.py
from django.urls import path

from flop_ics import views
from flop_ics.feeds import (
    RegenFeed,
    RoomEventFeed,
    StructuralGroupEventFeed,
    TransversalGroupEventFeed,
    TutorEventFeed,
)

app_name = "flop_ics"

urlpatterns = [
    path(r"", views.index, name="index"),
    path(r"tutor/<int:tutor_id>.ics", TutorEventFeed(), name="tutor"),
    path(r"room/<int:room_id>.ics", RoomEventFeed(), name="room"),
    path(
        r"structural_group/<int:group_id>.ics",
        StructuralGroupEventFeed(),
        name="structural_group",
    ),
    path(
        r"transversal_group/<int:group_id>.ics",
        TransversalGroupEventFeed(),
        name="transversal_group",
    ),
    path(r"regen/<int:dep_id>.ics", RegenFeed(), name="regen"),
]

back/flopedt-django/base/templates/base/departments.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}

{% if departments %}
<script type="text/javascript">
function goTo(url){
    location.href = url;
};
</script>
<div class="dept_container">
    <div class="dept_list">
        <p>
            {% trans "Please choose your department : " %}
        </p>
        <ul>
            {% for department in departments %}
            <li onclick="goTo('{% url 'base:edt-blank' department.abbrev %}');">{{ department.name }}</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% else %}
    <p>No departments are available.</p>
{% endif %}

{% endblock %}

back/flopedt-django/base/templates/base/edt-base.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% csrf_token %}

{% block title %} EDT {% endblock %}
{% block content %}

{% load static %}

<link rel="stylesheet" href="{% static 'base/better.css' %}?7" />
<script src="{% static 'base/d3.v4.min.js' %}"></script>
<script>
  var groupes_fi = "{% url 'api:groups:structural-tree' %}";
  var transversal_groupes_fi = "{% url 'api:groups:transversal-list' %}";

  var url_ttconstraint = "{% url 'api:ttapp:constraints-list' %}"
  var rooms_fi = "{% url 'api:rooms:all-list' %}";
  var constraints_fi = "{% url 'api:fetch:constraints-list' %}";
    
    var url_module = "{% url 'api:course:module-list' %}";
    var url_tutor = "{% url 'api:people:tutor-list' %}";
    var url_all_tutors = "{% url 'api:people:tutor_username-list' %}";
    
    var url_bknews = "{% url 'api:extra:bknews-list' %}";
    var url_quote = "{% url 'api:extra:random-quote-list' %}";

  var url_cours_pp = "{% url 'api:fetch:unscheduledcourses-list' %}";

  var url_weekdays = "{% url 'api:fetch:weekdays-list' %}";
  
    var url_contact = "{% url 'base:contact-blank' department %}";
    var url_login = "{% url "people:login" %}";
    var url_edt = "{% url 'base:edt-blank' department %}";

  var url_cours_pl = "{% url 'api:fetch:scheduledcourses-list' %}";


    var url_user_pref_changes = "{% url "base:user_pref_changes" department 0 0 '.' %}";
    url_user_pref_changes = url_user_pref_changes.slice(0, -9);

    var url_week_infos = "{% url 'api:extra:week-infos-list' %}";

    var url_major_versions = "{% url "TTapp:available_major_versions" department 0 %}" ;
    url_major_versions = url_major_versions.slice(0, -7);
    var url_check_swap = "{% url 'TTapp:check_swap' department 0 0%}" ;
    url_check_swap = url_check_swap.slice(0, -9) ;
    var url_delete_version = "{% url 'TTapp:delete_version' department 0 0 %}" ;
    url_delete_version = url_delete_version.slice(0, -9) ;
    var url_duplicate_version = "{% url 'TTapp:duplicate_version' department 0 0 %}" ;
    url_duplicate_version = url_duplicate_version.slice(0, -9) ;
    var url_delete_all_unused_versions = "{% url 'TTapp:delete_all_unused_versions' department 0 0 %}" ;
    url_delete_all_unused_versions = url_delete_all_unused_versions.slice(0, -7) ;
    var url_swap = "{% url 'TTapp:swap' department 0 0 0 %}" ;
    url_swap = url_swap.slice(0, -9) ;
    var url_reassign_rooms = "{% url 'TTapp:reassign_rooms' department 0 0 0 %}" ;
    url_reassign_rooms = url_reassign_rooms.slice(0, -9) ;
    var url_duplicate_in_other_periods = "{% url 'TTapp:duplicate_in_other_periods' department 0 0 0 %}" ;
    url_duplicate_in_other_periods = url_duplicate_in_other_periods.slice(0, -9) ;
    var url_fetch_extra_sched = "{% url 'api:fetch:extrasched-list' %}" ;
    var url_fetch_shared_rooms = "{% url 'base:fetch_shared_rooms' department 0 0 %}" ;
    url_fetch_shared_rooms = url_fetch_shared_rooms.slice(0, -7) ;
    var url_mail_auto = "{% url "base:email-proposal" department %}";
    var url_game = "{% url 'easter_egg:start_game' %}" ;
  var url_colors = "{% url 'displayweb:fetch_colors' department %}" ;
  var url_group_lunch = "{% url 'TTapp:fetch_group_lunch' department %}" ;
  var url_fetch_user_preferred_links = "{% url 'people:fetch_user_preferred_links' department %}" ;
  var url_fetch_group_preferred_links = "{% url 'base:fetch_group_preferred_links' department %}" ;
  var url_change_preferred_links = "{% url 'base:visio-pref' department %}" ;
  var url_fetch_physical_presence = "{% url 'people:fetch_physical_presence' department 0 0 %}" ;
  url_fetch_physical_presence = url_fetch_physical_presence.slice(0, -7) ;
  var url_change_physical_presence = "{% url 'people:change_physical_presence' 0 0 '.' %}" ;
  url_change_physical_presence = url_change_physical_presence.slice(0, -9) ;

    var department = "{{ dept }}" ;
    var week_year_list = {{ all_weeks| safe }};
    var week_init = +"{{ week }}";
    var year_init = +"{{ year }}";
  var department_settings = {{ department_settings | safe }} ;
  department_settings.mode['visio']=department_settings.mode['visio']=='True'?true:false;
  department_settings.time.bu = {} ;
    var days = {{ days | safe }} ;
  var csrftoken = '{{ csrf_token }}';
  if(!jQuery.fn.jquery.startsWith("1")){
      function csrfSafeMethod(method) {
          // these HTTP methods do not require CSRF protection
          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }
      $.ajaxSetup({
          beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
              }
          }
      });
  }
</script>

{% block script_variable %}{% endblock %}

<script type='text/javascript' src="{% static 'base/helpers.js' %}?2"></script>
<script type='text/javascript' src="{% static 'TTapp/side_panel.js' %}?2"></script>
<script type='text/javascript' src="{% static 'base/days.js' %}?2"></script>
<script type='text/javascript' src="{% static 'base/weeks.js' %}?2"></script>
<script type='text/javascript' src="{% static 'base/hours.js' %}?2"></script>
<script type='text/javascript' src="{% static 'base/svg.js' %}?2"></script>
<script type='text/javascript' src="{% static 'base/variables.js' %}?2"></script>
<script type='text/javascript' src="{% static 'base/intervals.js' %}?2"></script>
<script type='text/javascript' src="{% static 'base/week_change.js' %}?2"></script>
<script type='text/javascript' src="{% static 'base/transformation.js' %}?2"></script>
<script type='text/javascript' src="{% static 'base/creation.js' %}?2"></script>
<script type='text/javascript' src="{% static 'base/action.js' %}?2"></script>
<script type='text/javascript' src="{% static 'base/update.js' %}?2"></script>

{% block script_file %}{% endblock %}

{% endblock %}

back/flopedt-django/base/templates/base/presse papier.html
AIDE

Cliquer droit sur le cours en question, les salles disponibles apparaissent. Cliquer sur + pour choisir une salle non prévue pour ce cours. Ne pas oublier de valider tout changement.

Ici

Cliquer sur son pseudo (ses initiales) en haut à droite de la page.


Au moment de la génération de l'emploi du temps d'une semaine donnée, si aucune disponibilité n'est renseignée pour cette semaine, la semaine type définit les disponibilités.

Cliquer sur 			pour modifier son mot de passe

for a password reminder, or via "Login" at the top of the page.

pour un rappel de mot de passe, ou via "Se connecter" en haut de page.

DEPARTEMENTS :

"Veuillez choisir votre département :"

moduledescription :

"Modification de la description du module"

ROOM PREFERENCE : 

(Classement de vos salles préférées, pouvant contenir des égalités.)

SHOW DECALE : 

Cours annulé
Cours en attente
Cours placé en semaine

Comment ?

SHOW EDT

Vérifier élection
Élire cette copie
Dupliquer cette copie
Supprimer cette copie
Supprimer toutes les copies sauf la 0
Réassigner les salles

SHOW STYPE
Profs
Transformation en
Types de cours

statistic.html

Nombre de jours d'innocupation par salle

Nombre de cours donnés par professeur